---
- name: Ensure base packages present
  ansible.builtin.yum:
    name:
      - nginx
    state: present

- name: Deploy index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    mode: '0644'

- name: Configure login banner
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'

- name: Enable and start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
